name: Main

on: push

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.2
        with:
          java-version: 1.8
          distribution: adopt
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      - name: Build package
        run: mvn clean package

      - name: Tag package
        if: startsWith(github.ref, 'refs/tags/')
        run: cp ./target/keycloak-sentry-logger.jar ./dev.yakovlev_alexey-keycloak-sentry-logger-$GITHUB_REF_NAME.jar
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: dev.yakovlev_alexey-keycloak-sentry-logger-${{ github.ref_name }}.jar
  
